### ISSUE TITLE
clsx/prefer-objects-over-logical removes quotes when autofixing

### ISSUE THREAD

**Issue by raphaelbadia** [temoncher/eslint-plugin-clsx#6]
Hello, thank you for this plugin !

I'm trying it today and I found a small bug, when autofixing a condition, eslint-plugin-clsx removes the quotes entirely. I think in this case it should check for quotes and keep them when refactoring >

![CleanShot 2023-03-09 at 18 23 01](https://user-images.githubusercontent.com/1901628/224106403-e0693594-dd01-4263-a24f-433bd1520f16.gif)

**Comment by temoncher** [comment]
@raphaelbadia 
Yeah looks like a nasty bug! I'm pretty busy lately (as you can see by delay of this answer), I'll fix it when I have time to, no commitments tho

Did you end up disabling this rule or ditching the plugin entirely?

**Comment by raphaelbadia** [comment]
I first tried to fix it myself, failed, and ended up ditching the plugin completely because that was the more interesting rule for me and my team. But I'm watching the repo, will know if you happen to fix it 😄 If you don't, no worries!
