### ISSUE TITLE
`no-redundant-clsx` does not work with backtick strings (template literals)

### ISSUE THREAD

**Issue by YayC** [temoncher/eslint-plugin-clsx#7]
The `no-redundant-clsx` rule fails to report ``className=clsx(`foo`)``. It is correctly detected after changing it to `className=clsx('foo')`.

I think backtick strings also break other rules, but I haven't tested extensively.

**Comment by YayC** [comment]
I created a PR with a basic fix. Let me know if it looks ok, it definitely needs to be tested more as I haven't written eslint rules before. My quick test for ``className={clsx(`foo`)}`` worked

**Comment by YayC** [comment]
thanks for merging that in! sounds good, I can try to take a closer look later this week or next

**Comment by temoncher** [comment]
Added 0.0.4 to CHANGELOG.md
